### ISSUE TITLE
A course of action

### ISSUE THREAD

**Issue by kakirastern** [fridarode/autism_helpers#14]
Have you tried like maybe this in the future? http://www.msba.ust.hk/

**Comment by akirahirohito** [comment]
Who do you think you are? Telling me how to foul up my life because of your very American anti-intellectualism? Do you owe me anything? No. Do I owe you anything? No. Thank you but no thanks. For it is people like you who always think ill of the others who got us into a total anarchy America. Thou shall not hate.
